<?php

namespace App\Enums;

class AdminRoutEnum
{
    public static function format($as)
    {
        $data = [
            "login" => "登录",
            "checkCode" => "短信验证码",
            "retrievePassword" => "重置密码",
            "wechatLoginState" => "获取微信登录状态",
            "wechatBind" => "管理员绑定微信",
            "wechatLogin" => "登录状态-回调",
            "create-order" => "购买插件",
            "check-payment-status" => "查询插件订单状态",
            "wxPayNotify.sms" => "微信支付回调-购买短信",
            "sms.retrieve" => "重置密码-发送短信",
            "systemConfig" => "后台-初始化配置",
            "logout" => "退出",
            "enterPosition" => "进入平台",
            "sms.list" => "短信发送记录",
            "smsPay.list" => "短信购买订单",
            "miniUpload.version" => "获取小程序最新版本",
            "miniUpload.upload" => "上传小程序到草稿箱",
            "OpenWechat.draftbox" => "草稿箱",
            "OpenWechat.release" => "发布版本",
            "OpenWechat.templateList" => "小程序模板库列表",
            "OpenWechat.templateSelect" => "草稿转为小程序模板",
            "OpenWechat.template-delete" => "删除小程序模板",
            "admins.state" => "启用/禁用管理员",
            "admins.list" => "管理员列表",
            "admins.audit" => "管理员审核",
            "admins.recovery" => "管理员回收站",
            "admins.del" => "从回收站删除用户",
            "admins.restore" => "从回收站恢复用户",
            "apply.surver" => "平台概况",
            "apply.recycle" => "平台回收站",
            "apply.state" => "启用/拉黑平台",
            "apply.del" => "从回收站删除平台",
            "apply.restore" => "从回收站恢复平台",
            "apply.autio" => "店铺审核",
            "plugins" => "获取自己的插件",
            "config.get" => "获取配置",
            "config.create" => "新增配置",
            "config.update" => "更新配置",
            "loadMenus" => "获取自己的菜单",
            "changePassword" => "管理员修改密码",
            "profix" => "获取自己的信息",
            "checkForUpdates" => "检查版本更新",
            "updateSystem" => "版本更新",
            "system.sendSms" => "admin/system/sendSms",
            "system.createWechat" => "快速创建雄安程序",
            "system.getWechatList" => "获取注册小程序列表",
            "system.uploadImage" => "图片上传",
            "system.GetUpdateAnnouncementList" => "获取系统更新公告列表",
            "customer.getCustomerList" => "客服列表",
            "customer.saveCustomer" => "新增/更新客服",
            "customer.changeCustomer" => "启用/禁用客服",
            "admins.index" => "管理员列表",
            "admins.store" => "创建管理员",
            "admins.show" => "获取管理员详情",
            "admins.update" => "编辑管理员信息",
            "admins.destroy" => "删除管理员",
            "roles.index" => "角色列表",
            "roles.store" => "新增角色",
            "roles.show" => "获取角色详情",
            "roles.update" => "编辑角色",
            "roles.destroy" => "删除角色",
            "menus.index" => "菜单列表",
            "menus.store" => "新增菜单",
            "menus.show" => "获取菜单那详情",
            "menus.update" => "编辑菜单",
            "menus.destroy" => "删除菜单",
            "permissions.index" => "权限列表",
            "permissions.store" => "新增权限",
            "permissions.show" => "获取权限详情",
            "permissions.update" => "编辑权限",
            "permissions.destroy" => "删除权限",
            "permission_groups.index" => "权限分组列表",
            "permission_groups.store" => "新增权限分组",
            "permission_groups.show" => "获取权限分组详情",
            "permission_groups.update" => "编辑权限分组",
            "permission_groups.destroy" => "删除权限分组",
            "muster.index" => "admin/muster",
            "muster.store" => "admin/muster",
            "muster.show" => "admin/muster/{muster}",
            "muster.update" => "admin/muster/{muster}",
            "muster.destroy" => "admin/muster/{muster}",
            "apply.index" => "平台列表",
            "apply.store" => "新增平台",
            "apply.show" => "获取平台信息",
            "apply.update" => "编辑平台信息",
            "apply.destroy" => "删除平台",
            "handleLog.index" => "日志记录列表",
            "handleLog.store" => "admin/handleLog",
            "handleLog.show" => "admin/handleLog/{handleLog}",
            "handleLog.update" => "admin/handleLog/{handleLog}",
            "handleLog.destroy" => "admin/handleLog/{handleLog}",
            "news.index" => "公告列表",
            "news.store" => "新增公告",
            "news.show" => "公告详情",
            "news.update" => "编辑公告",
            "news.destroy" => "删除公告",
            "admin_group.index" => "用户分组列表",
            "admin_group.store" => "新增用户分组",
            "admin_group.show" => "用户分组详情",
            "admin_group.update" => "编辑用户分组",
            "admin_group.destroy" => "删除用户分组"
        ];
        return isset($data[$as])  ? $data[$as] : $as;
    }
}
