
#项目名
[program:laravels]
#脚本执行命令
command= php /data/bin/laravels restart
#supervisor启动的时候是否随着同时启动，默认True
autostart=true
#当程序exit的时候，这个program不会自动重启,默认unexpected，设置子进程挂掉后自动重启的情况，有三个选项，false,unexpected和true。如果为false的时候，无论什么情况下，都不会被重新启动，如果为unexpected，只有当进程的退出了不在下面的exitcodes里面定义的
autorestart=true
#启动失败时的最多重试次数
startretries=3
#发送SIGKILL前的等待时间
stopwaitsecs=10
#用户名
user=root
#日志输出
log_stdout=true
log_stderr=true
logfile=/tmp/echo_time.log
logfile_maxbytes=1MB
logfile_backups=10
#stdout日志文件大小，默认 50MB
stdout_logfile_maxbytes=20MB
#stdout日志文件备份数
stdout_logfile_backups=20
#把stderr重定向到stdout，默认 false
redirect_stderr=true
stdout_logfile=/data/supervisord.log
